# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculator.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x63\x61lculator.proto\"\x17\n\x06Number\x12\r\n\x05value\x18\x01 \x01(\x02\"+\n\x07Numbers\x12\x0f\n\x07number1\x18\x02 \x01(\x02\x12\x0f\n\x07number2\x18\x03 \x01(\x02\x32\xb5\x01\n\nCalculator\x12 \n\nSquareRoot\x12\x07.Number\x1a\x07.Number\"\x00\x12\x1a\n\x03Sum\x12\x08.Numbers\x1a\x07.Number\"\x00\x12!\n\nDifference\x12\x08.Numbers\x1a\x07.Number\"\x00\x12%\n\x0eMultiplication\x12\x08.Numbers\x1a\x07.Number\"\x00\x12\x1f\n\x08\x44ivision\x12\x08.Numbers\x1a\x07.Number\"\x00\x62\x06proto3')
)




_NUMBER = _descriptor.Descriptor(
  name='Number',
  full_name='Number',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Number.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=43,
)


_NUMBERS = _descriptor.Descriptor(
  name='Numbers',
  full_name='Numbers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number1', full_name='Numbers.number1', index=0,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number2', full_name='Numbers.number2', index=1,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['Number'] = _NUMBER
DESCRIPTOR.message_types_by_name['Numbers'] = _NUMBERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Number = _reflection.GeneratedProtocolMessageType('Number', (_message.Message,), dict(
  DESCRIPTOR = _NUMBER,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:Number)
  ))
_sym_db.RegisterMessage(Number)

Numbers = _reflection.GeneratedProtocolMessageType('Numbers', (_message.Message,), dict(
  DESCRIPTOR = _NUMBERS,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:Numbers)
  ))
_sym_db.RegisterMessage(Numbers)



_CALCULATOR = _descriptor.ServiceDescriptor(
  name='Calculator',
  full_name='Calculator',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=91,
  serialized_end=272,
  methods=[
  _descriptor.MethodDescriptor(
    name='SquareRoot',
    full_name='Calculator.SquareRoot',
    index=0,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_NUMBER,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Sum',
    full_name='Calculator.Sum',
    index=1,
    containing_service=None,
    input_type=_NUMBERS,
    output_type=_NUMBER,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Difference',
    full_name='Calculator.Difference',
    index=2,
    containing_service=None,
    input_type=_NUMBERS,
    output_type=_NUMBER,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Multiplication',
    full_name='Calculator.Multiplication',
    index=3,
    containing_service=None,
    input_type=_NUMBERS,
    output_type=_NUMBER,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Division',
    full_name='Calculator.Division',
    index=4,
    containing_service=None,
    input_type=_NUMBERS,
    output_type=_NUMBER,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATOR)

DESCRIPTOR.services_by_name['Calculator'] = _CALCULATOR

# @@protoc_insertion_point(module_scope)
