# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import calculator_pb2 as calculator__pb2


class CalculatorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SquareRoot = channel.unary_unary(
        '/Calculator/SquareRoot',
        request_serializer=calculator__pb2.Number.SerializeToString,
        response_deserializer=calculator__pb2.Number.FromString,
        )
    self.Sum = channel.unary_unary(
        '/Calculator/Sum',
        request_serializer=calculator__pb2.Numbers.SerializeToString,
        response_deserializer=calculator__pb2.Number.FromString,
        )
    self.Difference = channel.unary_unary(
        '/Calculator/Difference',
        request_serializer=calculator__pb2.Numbers.SerializeToString,
        response_deserializer=calculator__pb2.Number.FromString,
        )
    self.Multiplication = channel.unary_unary(
        '/Calculator/Multiplication',
        request_serializer=calculator__pb2.Numbers.SerializeToString,
        response_deserializer=calculator__pb2.Number.FromString,
        )
    self.Division = channel.unary_unary(
        '/Calculator/Division',
        request_serializer=calculator__pb2.Numbers.SerializeToString,
        response_deserializer=calculator__pb2.Number.FromString,
        )


class CalculatorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SquareRoot(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Sum(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Difference(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Multiplication(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Division(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CalculatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SquareRoot': grpc.unary_unary_rpc_method_handler(
          servicer.SquareRoot,
          request_deserializer=calculator__pb2.Number.FromString,
          response_serializer=calculator__pb2.Number.SerializeToString,
      ),
      'Sum': grpc.unary_unary_rpc_method_handler(
          servicer.Sum,
          request_deserializer=calculator__pb2.Numbers.FromString,
          response_serializer=calculator__pb2.Number.SerializeToString,
      ),
      'Difference': grpc.unary_unary_rpc_method_handler(
          servicer.Difference,
          request_deserializer=calculator__pb2.Numbers.FromString,
          response_serializer=calculator__pb2.Number.SerializeToString,
      ),
      'Multiplication': grpc.unary_unary_rpc_method_handler(
          servicer.Multiplication,
          request_deserializer=calculator__pb2.Numbers.FromString,
          response_serializer=calculator__pb2.Number.SerializeToString,
      ),
      'Division': grpc.unary_unary_rpc_method_handler(
          servicer.Division,
          request_deserializer=calculator__pb2.Numbers.FromString,
          response_serializer=calculator__pb2.Number.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Calculator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
