apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vessel-deployment
  namespace: shippy-grpc
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: vessel-app
    spec:
        containers:
        - name: vessel
          image: gcr.io/gcptraining-17042017/python-grpc-microservice/vessel:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 50052
            name: vessel-port
