
apiVersion: v1
kind: Service
metadata:
  name: vessel
  namespace: shippy-grpc
  labels:
    app: vessel
spec:
  clusterIP: None
  ports:
  - port: 50052
    protocol: TCP
    targetPort: 50052
  selector:
    app: vessel
