apiVersion: v1
kind: Service
metadata:
  name: vessel-svc
  namespace: shippy-grpc
spec:
  ports:
  - port: 50052
    protocol: TCP
    targetPort: 50052
    name: vessel-grpc
  selector:
    app: vessel-app
