# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: article.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='article.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rarticle.proto\"\x14\n\x06UserId\x12\n\n\x02id\x18\x01 \x01(\x05\"#\n\x10\x41rticlesResponse\x12\x0f\n\x07\x61rticle\x18\x01 \x01(\t25\n\x07\x41rticle\x12*\n\nGetArticle\x12\x07.UserId\x1a\x11.ArticlesResponse\"\x00\x62\x06proto3')
)




_USERID = _descriptor.Descriptor(
  name='UserId',
  full_name='UserId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='UserId.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=37,
)


_ARTICLESRESPONSE = _descriptor.Descriptor(
  name='ArticlesResponse',
  full_name='ArticlesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='article', full_name='ArticlesResponse.article', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['UserId'] = _USERID
DESCRIPTOR.message_types_by_name['ArticlesResponse'] = _ARTICLESRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserId = _reflection.GeneratedProtocolMessageType('UserId', (_message.Message,), dict(
  DESCRIPTOR = _USERID,
  __module__ = 'article_pb2'
  # @@protoc_insertion_point(class_scope:UserId)
  ))
_sym_db.RegisterMessage(UserId)

ArticlesResponse = _reflection.GeneratedProtocolMessageType('ArticlesResponse', (_message.Message,), dict(
  DESCRIPTOR = _ARTICLESRESPONSE,
  __module__ = 'article_pb2'
  # @@protoc_insertion_point(class_scope:ArticlesResponse)
  ))
_sym_db.RegisterMessage(ArticlesResponse)



_ARTICLE = _descriptor.ServiceDescriptor(
  name='Article',
  full_name='Article',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=76,
  serialized_end=129,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetArticle',
    full_name='Article.GetArticle',
    index=0,
    containing_service=None,
    input_type=_USERID,
    output_type=_ARTICLESRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ARTICLE)

DESCRIPTOR.services_by_name['Article'] = _ARTICLE

# @@protoc_insertion_point(module_scope)
