# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import user_pb2 as user__pb2


class UserServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetUser = channel.unary_unary(
        '/UserService/GetUser',
        request_serializer=user__pb2.GetRequest.SerializeToString,
        response_deserializer=user__pb2.Response.FromString,
        )
    self.CreateUser = channel.unary_unary(
        '/UserService/CreateUser',
        request_serializer=user__pb2.User.SerializeToString,
        response_deserializer=user__pb2.Response.FromString,
        )
    self.GetUserArticle = channel.unary_unary(
        '/UserService/GetUserArticle',
        request_serializer=user__pb2.ArticleRequest.SerializeToString,
        response_deserializer=user__pb2.ArticleResponse.FromString,
        )


class UserServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserArticle(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetUser': grpc.unary_unary_rpc_method_handler(
          servicer.GetUser,
          request_deserializer=user__pb2.GetRequest.FromString,
          response_serializer=user__pb2.Response.SerializeToString,
      ),
      'CreateUser': grpc.unary_unary_rpc_method_handler(
          servicer.CreateUser,
          request_deserializer=user__pb2.User.FromString,
          response_serializer=user__pb2.Response.SerializeToString,
      ),
      'GetUserArticle': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserArticle,
          request_deserializer=user__pb2.ArticleRequest.FromString,
          response_serializer=user__pb2.ArticleResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'UserService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
