## vessel_servicec.yaml

---
apiVersion: v1
kind: Service
metadata:
  name: vessel
  namespace: shippy-grpc
  labels:
    app: vessel
spec:
  clusterIP: None
  ports:
  - port: 50052
    protocol: TCP
    targetPort: 50052
  selector:
    app: vessel

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vessel
  namespace: shippy-grpc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vessel
  template:
    metadata:
      labels:
        app: vessel
    spec:
        containers:
        - name: vessel
          image: gcr.io/gcptraining-17042017/python-grpc-microservice/vessel:ssl
          imagePullPolicy: Always
          ports:
          - containerPort: 50052
            name: vessel-port
