
## shipment_service.yaml

---
apiVersion: v1
kind: Service
metadata:
  name: shipment
  namespace: kube-system
  labels:
    app: shipment
spec:
  clusterIP: None
  ports:
  - port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: shipment

---


apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: shipment
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipment
  template:
    metadata:
      labels:
        app: shipment
    spec:
        containers:
        - name: shipment
          image: gcr.io/pso-suchit/grpc-microservice/shipment:nginx
          imagePullPolicy: Always
          ports:
          - containerPort: 50051
            name: ship-port
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "64Mi"
              cpu: "250m"
