# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vessel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vessel.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0cvessel.proto\",\n\nVesselItem\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nmax_weight\x18\x02 \x01(\x05\"\"\n\x10GetVesselRequest\x12\x0e\n\x06weight\x18\x01 \x01(\x05\x32\x37\n\x06Vessel\x12-\n\tGetVessel\x12\x11.GetVesselRequest\x1a\x0b.VesselItem\"\x00\x62\x06proto3')
)




_VESSELITEM = _descriptor.Descriptor(
  name='VesselItem',
  full_name='VesselItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='VesselItem.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_weight', full_name='VesselItem.max_weight', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=60,
)


_GETVESSELREQUEST = _descriptor.Descriptor(
  name='GetVesselRequest',
  full_name='GetVesselRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='weight', full_name='GetVesselRequest.weight', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['VesselItem'] = _VESSELITEM
DESCRIPTOR.message_types_by_name['GetVesselRequest'] = _GETVESSELREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VesselItem = _reflection.GeneratedProtocolMessageType('VesselItem', (_message.Message,), dict(
  DESCRIPTOR = _VESSELITEM,
  __module__ = 'vessel_pb2'
  # @@protoc_insertion_point(class_scope:VesselItem)
  ))
_sym_db.RegisterMessage(VesselItem)

GetVesselRequest = _reflection.GeneratedProtocolMessageType('GetVesselRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETVESSELREQUEST,
  __module__ = 'vessel_pb2'
  # @@protoc_insertion_point(class_scope:GetVesselRequest)
  ))
_sym_db.RegisterMessage(GetVesselRequest)



_VESSEL = _descriptor.ServiceDescriptor(
  name='Vessel',
  full_name='Vessel',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=98,
  serialized_end=153,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetVessel',
    full_name='Vessel.GetVessel',
    index=0,
    containing_service=None,
    input_type=_GETVESSELREQUEST,
    output_type=_VESSELITEM,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VESSEL)

DESCRIPTOR.services_by_name['Vessel'] = _VESSEL

# @@protoc_insertion_point(module_scope)
