# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import vessel_pb2 as vessel__pb2


class VesselStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetVessel = channel.unary_unary(
        '/Vessel/GetVessel',
        request_serializer=vessel__pb2.GetVesselRequest.SerializeToString,
        response_deserializer=vessel__pb2.VesselItem.FromString,
        )


class VesselServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetVessel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VesselServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetVessel': grpc.unary_unary_rpc_method_handler(
          servicer.GetVessel,
          request_deserializer=vessel__pb2.GetVesselRequest.FromString,
          response_serializer=vessel__pb2.VesselItem.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Vessel', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
