# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import shipment_pb2 as shipment__pb2


class ShipmentStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetShipment = channel.unary_unary(
        '/Shipment/GetShipment',
        request_serializer=shipment__pb2.GetShipmentRequest.SerializeToString,
        response_deserializer=shipment__pb2.ShipmentItem.FromString,
        )
    self.GetCarrierForShipment = channel.unary_unary(
        '/Shipment/GetCarrierForShipment',
        request_serializer=shipment__pb2.ShipmentItem.SerializeToString,
        response_deserializer=shipment__pb2.ShipmentCarrier.FromString,
        )


class ShipmentServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetShipment(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCarrierForShipment(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ShipmentServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetShipment': grpc.unary_unary_rpc_method_handler(
          servicer.GetShipment,
          request_deserializer=shipment__pb2.GetShipmentRequest.FromString,
          response_serializer=shipment__pb2.ShipmentItem.SerializeToString,
      ),
      'GetCarrierForShipment': grpc.unary_unary_rpc_method_handler(
          servicer.GetCarrierForShipment,
          request_deserializer=shipment__pb2.ShipmentItem.FromString,
          response_serializer=shipment__pb2.ShipmentCarrier.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Shipment', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
