apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: server2
  namespace: py-grpc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server2
  template:
    metadata:
      labels:
        app: server2
    spec:
        containers:
        - name: server2
          image: gcr.io/gcptraining-17042017/python-grpc-microservice/server2:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 50052
            name: server2-port
