apiVersion: v1
kind: Service
metadata:
  name: server2
  namespace: py-grpc
  labels:
    app: server2
spec:
  type: LoadBalancer
  ports:
  - port: 50052
    protocol: TCP
    targetPort: 50052
  selector:
    app: server2
