## client_service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: istio-system
  labels:
    app: client
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: client
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: client
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
        containers:
        - name: client
          image: gcr.io/grcp-on-gke/grpc-microservice/client:nginx
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
            name: client-port
