## client_service.yaml

---
apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: kube-system
  labels:
    app: client
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: client

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: client
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
        containers:
        - name: client
          image: gcr.io/pso-suchit/grpc-microservice/client:nginx
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
            name: client-port
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "250m"
