# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: carrier.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='carrier.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rcarrier.proto\"-\n\x0b\x43\x61rrierItem\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nmax_weight\x18\x02 \x01(\x05\"#\n\x11GetCarrierRequest\x12\x0e\n\x06weight\x18\x01 \x01(\x05\x32;\n\x07\x43\x61rrier\x12\x30\n\nGetCarrier\x12\x12.GetCarrierRequest\x1a\x0c.CarrierItem\"\x00\x62\x06proto3')
)




_CARRIERITEM = _descriptor.Descriptor(
  name='CarrierItem',
  full_name='CarrierItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CarrierItem.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_weight', full_name='CarrierItem.max_weight', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=62,
)


_GETCARRIERREQUEST = _descriptor.Descriptor(
  name='GetCarrierRequest',
  full_name='GetCarrierRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='weight', full_name='GetCarrierRequest.weight', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=99,
)

DESCRIPTOR.message_types_by_name['CarrierItem'] = _CARRIERITEM
DESCRIPTOR.message_types_by_name['GetCarrierRequest'] = _GETCARRIERREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CarrierItem = _reflection.GeneratedProtocolMessageType('CarrierItem', (_message.Message,), dict(
  DESCRIPTOR = _CARRIERITEM,
  __module__ = 'carrier_pb2'
  # @@protoc_insertion_point(class_scope:CarrierItem)
  ))
_sym_db.RegisterMessage(CarrierItem)

GetCarrierRequest = _reflection.GeneratedProtocolMessageType('GetCarrierRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETCARRIERREQUEST,
  __module__ = 'carrier_pb2'
  # @@protoc_insertion_point(class_scope:GetCarrierRequest)
  ))
_sym_db.RegisterMessage(GetCarrierRequest)



_CARRIER = _descriptor.ServiceDescriptor(
  name='Carrier',
  full_name='Carrier',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=101,
  serialized_end=160,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetCarrier',
    full_name='Carrier.GetCarrier',
    index=0,
    containing_service=None,
    input_type=_GETCARRIERREQUEST,
    output_type=_CARRIERITEM,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CARRIER)

DESCRIPTOR.services_by_name['Carrier'] = _CARRIER

# @@protoc_insertion_point(module_scope)
