apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: client-deployment
  namespace: shippy-grpc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: client-app
    spec:
        containers:
        - name: client
          image: gcr.io/gcptraining-17042017/python-grpc-microservice/client:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
            name: client-port
