
apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: shippy-grpc
  labels:
    app: client
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: client
