apiVersion: v1
kind: Service
metadata:
  name: client-svc
  namespace: shippy-grpc
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    name: client-grpc
  selector:
    app: client-app
