# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import consignment_pb2 as consignment__pb2


class ShippingStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetConsignment = channel.unary_unary(
        '/Shipping/GetConsignment',
        request_serializer=consignment__pb2.GetConsignmentRequest.SerializeToString,
        response_deserializer=consignment__pb2.Consignment.FromString,
        )
    self.GetVesselForConsignment = channel.unary_unary(
        '/Shipping/GetVesselForConsignment',
        request_serializer=consignment__pb2.Consignment.SerializeToString,
        response_deserializer=consignment__pb2.ConsignmentVessel.FromString,
        )


class ShippingServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetConsignment(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetVesselForConsignment(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ShippingServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetConsignment': grpc.unary_unary_rpc_method_handler(
          servicer.GetConsignment,
          request_deserializer=consignment__pb2.GetConsignmentRequest.FromString,
          response_serializer=consignment__pb2.Consignment.SerializeToString,
      ),
      'GetVesselForConsignment': grpc.unary_unary_rpc_method_handler(
          servicer.GetVesselForConsignment,
          request_deserializer=consignment__pb2.Consignment.FromString,
          response_serializer=consignment__pb2.ConsignmentVessel.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Shipping', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
