# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consignment.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='consignment.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x63onsignment.proto\"7\n\x0b\x43onsignment\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06weight\x18\x03 \x01(\x05\"3\n\x11\x43onsignmentVessel\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nmax_weight\x18\x02 \x01(\x05\"/\n\x15GetConsignmentRequest\x12\x16\n\x0e\x63onsignment_id\x18\x01 \x01(\x05\x32\x83\x01\n\x08Shipping\x12\x38\n\x0eGetConsignment\x12\x16.GetConsignmentRequest\x1a\x0c.Consignment\"\x00\x12=\n\x17GetVesselForConsignment\x12\x0c.Consignment\x1a\x12.ConsignmentVessel\"\x00\x62\x06proto3')
)




_CONSIGNMENT = _descriptor.Descriptor(
  name='Consignment',
  full_name='Consignment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Consignment.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='Consignment.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weight', full_name='Consignment.weight', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=76,
)


_CONSIGNMENTVESSEL = _descriptor.Descriptor(
  name='ConsignmentVessel',
  full_name='ConsignmentVessel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ConsignmentVessel.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_weight', full_name='ConsignmentVessel.max_weight', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=129,
)


_GETCONSIGNMENTREQUEST = _descriptor.Descriptor(
  name='GetConsignmentRequest',
  full_name='GetConsignmentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='consignment_id', full_name='GetConsignmentRequest.consignment_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=178,
)

DESCRIPTOR.message_types_by_name['Consignment'] = _CONSIGNMENT
DESCRIPTOR.message_types_by_name['ConsignmentVessel'] = _CONSIGNMENTVESSEL
DESCRIPTOR.message_types_by_name['GetConsignmentRequest'] = _GETCONSIGNMENTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Consignment = _reflection.GeneratedProtocolMessageType('Consignment', (_message.Message,), dict(
  DESCRIPTOR = _CONSIGNMENT,
  __module__ = 'consignment_pb2'
  # @@protoc_insertion_point(class_scope:Consignment)
  ))
_sym_db.RegisterMessage(Consignment)

ConsignmentVessel = _reflection.GeneratedProtocolMessageType('ConsignmentVessel', (_message.Message,), dict(
  DESCRIPTOR = _CONSIGNMENTVESSEL,
  __module__ = 'consignment_pb2'
  # @@protoc_insertion_point(class_scope:ConsignmentVessel)
  ))
_sym_db.RegisterMessage(ConsignmentVessel)

GetConsignmentRequest = _reflection.GeneratedProtocolMessageType('GetConsignmentRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETCONSIGNMENTREQUEST,
  __module__ = 'consignment_pb2'
  # @@protoc_insertion_point(class_scope:GetConsignmentRequest)
  ))
_sym_db.RegisterMessage(GetConsignmentRequest)



_SHIPPING = _descriptor.ServiceDescriptor(
  name='Shipping',
  full_name='Shipping',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=181,
  serialized_end=312,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetConsignment',
    full_name='Shipping.GetConsignment',
    index=0,
    containing_service=None,
    input_type=_GETCONSIGNMENTREQUEST,
    output_type=_CONSIGNMENT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetVesselForConsignment',
    full_name='Shipping.GetVesselForConsignment',
    index=1,
    containing_service=None,
    input_type=_CONSIGNMENT,
    output_type=_CONSIGNMENTVESSEL,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SHIPPING)

DESCRIPTOR.services_by_name['Shipping'] = _SHIPPING

# @@protoc_insertion_point(module_scope)
