# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shipment.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shipment.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0eshipment.proto\"8\n\x0cShipmentItem\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06weight\x18\x03 \x01(\x05\"1\n\x0fShipmentCarrier\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nmax_weight\x18\x02 \x01(\x05\")\n\x12GetShipmentRequest\x12\x13\n\x0bshipment_id\x18\x01 \x01(\x05\x32{\n\x08Shipment\x12\x33\n\x0bGetShipment\x12\x13.GetShipmentRequest\x1a\r.ShipmentItem\"\x00\x12:\n\x15GetCarrierForShipment\x12\r.ShipmentItem\x1a\x10.ShipmentCarrier\"\x00\x62\x06proto3')
)




_SHIPMENTITEM = _descriptor.Descriptor(
  name='ShipmentItem',
  full_name='ShipmentItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ShipmentItem.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ShipmentItem.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weight', full_name='ShipmentItem.weight', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=74,
)


_SHIPMENTCARRIER = _descriptor.Descriptor(
  name='ShipmentCarrier',
  full_name='ShipmentCarrier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ShipmentCarrier.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_weight', full_name='ShipmentCarrier.max_weight', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=125,
)


_GETSHIPMENTREQUEST = _descriptor.Descriptor(
  name='GetShipmentRequest',
  full_name='GetShipmentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shipment_id', full_name='GetShipmentRequest.shipment_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=168,
)

DESCRIPTOR.message_types_by_name['ShipmentItem'] = _SHIPMENTITEM
DESCRIPTOR.message_types_by_name['ShipmentCarrier'] = _SHIPMENTCARRIER
DESCRIPTOR.message_types_by_name['GetShipmentRequest'] = _GETSHIPMENTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ShipmentItem = _reflection.GeneratedProtocolMessageType('ShipmentItem', (_message.Message,), dict(
  DESCRIPTOR = _SHIPMENTITEM,
  __module__ = 'shipment_pb2'
  # @@protoc_insertion_point(class_scope:ShipmentItem)
  ))
_sym_db.RegisterMessage(ShipmentItem)

ShipmentCarrier = _reflection.GeneratedProtocolMessageType('ShipmentCarrier', (_message.Message,), dict(
  DESCRIPTOR = _SHIPMENTCARRIER,
  __module__ = 'shipment_pb2'
  # @@protoc_insertion_point(class_scope:ShipmentCarrier)
  ))
_sym_db.RegisterMessage(ShipmentCarrier)

GetShipmentRequest = _reflection.GeneratedProtocolMessageType('GetShipmentRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETSHIPMENTREQUEST,
  __module__ = 'shipment_pb2'
  # @@protoc_insertion_point(class_scope:GetShipmentRequest)
  ))
_sym_db.RegisterMessage(GetShipmentRequest)



_SHIPMENT = _descriptor.ServiceDescriptor(
  name='Shipment',
  full_name='Shipment',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=170,
  serialized_end=293,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetShipment',
    full_name='Shipment.GetShipment',
    index=0,
    containing_service=None,
    input_type=_GETSHIPMENTREQUEST,
    output_type=_SHIPMENTITEM,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetCarrierForShipment',
    full_name='Shipment.GetCarrierForShipment',
    index=1,
    containing_service=None,
    input_type=_SHIPMENTITEM,
    output_type=_SHIPMENTCARRIER,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SHIPMENT)

DESCRIPTOR.services_by_name['Shipment'] = _SHIPMENT

# @@protoc_insertion_point(module_scope)
