## carrier_servicec.yaml

---
apiVersion: v1
kind: Service
metadata:
  name: carrier
  namespace: kube-system
  labels:
    app: carrier
spec:
  clusterIP: None
  ports:
  - port: 50052
    protocol: TCP
    targetPort: 50052
  selector:
    app: carrier

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: carrier
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: carrier
  template:
    metadata:
      labels:
        app: carrier
    spec:
        containers:
        - name: carrier
          image: gcr.io/pso-suchit/grpc-microservice/carrier:nginx
          imagePullPolicy: Always
          ports:
          - containerPort: 50052
            name: carrier-port
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "64Mi"
              cpu: "250m"
