## carrier_servicec.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: carrier
  namespace: istio-system
  labels:
    app: carrier
spec:
  type: NodePort
  ports:
  - port: 50052
    protocol: TCP
    name: grpc
    targetPort: 50052
  selector:
    app: carrier
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: carrier
  namespace: istio-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: carrier
  template:
    metadata:
      labels:
        app: carrier
    spec:
        containers:
        - name: carrier
          image: gcr.io/grcp-on-gke/grpc-microservice/carrier:nginx
          imagePullPolicy: Always
          ports:
          - containerPort: 50052
            name: carrier-port
